### ISSUE TITLE
Does not work with LibreOffice 4.0

### ISSUE THREAD

**Issue by ingolfschaefer** [zotero/zotero-libreoffice-integration#8]
I gave LibreOffice 4 Beta 2 & RC 1 a test, but they do not work with the Zotero extension. I installed the plugin manually and it installs fine, but does not work. When pressing the insert ciation button LibreOffice complains that: XDocumentInfoSupplier class is not found.

I checked on Linux (Ubuntu 12.10, 64bit) and MacOS X 10.8

Best,

Ingolf

Shell output on Linux:
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: com/sun/star/document/XDocumentInfoSupplier
at org.zotero.integration.ooo.comp.Properties.<init>(Properties.java:44)
at org.zotero.integration.ooo.comp.Document.<init>(Document.java:120)
at org.zotero.integration.ooo.comp.Application.getActiveDocument(Application.java:49)
at org.zotero.integration.ooo.comp.CommMessage.execute(CommMessage.java:59)
at org.zotero.integration.ooo.comp.CommMessage.getBytes(CommMessage.java:40)
at org.zotero.integration.ooo.comp.CommServer.run(CommServer.java:60)
at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ClassNotFoundException: com.sun.star.document.XDocumentInfoSupplier
at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
... 7 more
